# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_CaesarCipher(object):
    def setupUi(self, CaesarCipher):
        CaesarCipher.setObjectName("CaesarCipher")
        CaesarCipher.resize(550, 500)
        self.centralwidget = QtWidgets.QWidget(CaesarCipher)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CaecarCipher = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.CaecarCipher.setFont(font)
        self.CaecarCipher.setAlignment(QtCore.Qt.AlignCenter)
        self.CaecarCipher.setObjectName("CaecarCipher")
        self.verticalLayout.addWidget(self.CaecarCipher)
        self.TTCN = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.TTCN.setFont(font)
        self.TTCN.setAlignment(QtCore.Qt.AlignCenter)
        self.TTCN.setObjectName("TTCN")
        self.verticalLayout.addWidget(self.TTCN)
        self.PlainText = QtWidgets.QLabel(self.centralwidget)
        self.PlainText.setObjectName("PlainText")
        self.verticalLayout.addWidget(self.PlainText)
        self.plaintext_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaintext_txt.setObjectName("plaintext_txt")
        self.verticalLayout.addWidget(self.plaintext_txt)
        self.Key = QtWidgets.QLabel(self.centralwidget)
        self.Key.setObjectName("Key")
        self.verticalLayout.addWidget(self.Key)
        self.key_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.key_txt.setObjectName("key_txt")
        self.verticalLayout.addWidget(self.key_txt)
        self.CipherText = QtWidgets.QLabel(self.centralwidget)
        self.CipherText.setTextFormat(QtCore.Qt.AutoText)
        self.CipherText.setObjectName("CipherText")
        self.verticalLayout.addWidget(self.CipherText)
        self.ciphertext_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ciphertext_txt.setObjectName("ciphertext_txt")
        self.verticalLayout.addWidget(self.ciphertext_txt)
        self.decrypt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt_btn.setObjectName("decrypt_btn")
        self.verticalLayout.addWidget(self.decrypt_btn)
        self.encrypt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt_btn.setObjectName("encrypt_btn")
        self.verticalLayout.addWidget(self.encrypt_btn)
        CaesarCipher.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CaesarCipher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 22))
        self.menubar.setObjectName("menubar")
        CaesarCipher.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CaesarCipher)
        self.statusbar.setObjectName("statusbar")
        CaesarCipher.setStatusBar(self.statusbar)

        self.retranslateUi(CaesarCipher)
        QtCore.QMetaObject.connectSlotsByName(CaesarCipher)

    def retranslateUi(self, CaesarCipher):
        _translate = QtCore.QCoreApplication.translate
        CaesarCipher.setWindowTitle(_translate("CaesarCipher", "MainWindow"))
        self.CaecarCipher.setText(_translate("CaesarCipher", "Caesar Cipher"))
        self.TTCN.setText(_translate("CaesarCipher", "Danh Minh Quốc - 2280618774"))
        self.PlainText.setText(_translate("CaesarCipher", "Plain_text:"))
        self.Key.setText(_translate("CaesarCipher", "Key:"))
        self.CipherText.setText(_translate("CaesarCipher", "Cipher_text:"))
        self.decrypt_btn.setText(_translate("CaesarCipher", "Decrypt"))
        self.encrypt_btn.setText(_translate("CaesarCipher", "Encrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CaesarCipher = QtWidgets.QMainWindow()
    ui = Ui_CaesarCipher()
    ui.setupUi(CaesarCipher)
    CaesarCipher.show()
    sys.exit(app.exec_())
