# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_Playfair(object):
    def setupUi(self, Playfair):
        Playfair.setObjectName("Playfair")
        Playfair.resize(550, 500)
        self.centralwidget = QtWidgets.QWidget(Playfair)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PlayfairCipher = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PlayfairCipher.setFont(font)
        self.PlayfairCipher.setAlignment(QtCore.Qt.AlignCenter)
        self.PlayfairCipher.setObjectName("PlayfairCipher")
        self.verticalLayout.addWidget(self.PlayfairCipher)
        self.TTCN = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.TTCN.setFont(font)
        self.TTCN.setAlignment(QtCore.Qt.AlignCenter)
        self.TTCN.setObjectName("TTCN")
        self.verticalLayout.addWidget(self.TTCN)
        self.PlainText = QtWidgets.QLabel(self.centralwidget)
        self.PlainText.setObjectName("PlainText")
        self.verticalLayout.addWidget(self.PlainText)
        self.plaintext_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaintext_txt.setObjectName("plaintext_txt")
        self.verticalLayout.addWidget(self.plaintext_txt)
        self.Key = QtWidgets.QLabel(self.centralwidget)
        self.Key.setObjectName("Key")
        self.verticalLayout.addWidget(self.Key)
        self.key_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.key_txt.setObjectName("key_txt")
        self.verticalLayout.addWidget(self.key_txt)
        self.CipherText = QtWidgets.QLabel(self.centralwidget)
        self.CipherText.setTextFormat(QtCore.Qt.AutoText)
        self.CipherText.setObjectName("CipherText")
        self.verticalLayout.addWidget(self.CipherText)
        self.ciphertext_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ciphertext_txt.setObjectName("ciphertext_txt")
        self.verticalLayout.addWidget(self.ciphertext_txt)
        self.decrypt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt_btn.setObjectName("decrypt_btn")
        self.verticalLayout.addWidget(self.decrypt_btn)
        self.encrypt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt_btn.setObjectName("encrypt_btn")
        self.verticalLayout.addWidget(self.encrypt_btn)
        Playfair.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Playfair)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 22))
        self.menubar.setObjectName("menubar")
        Playfair.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Playfair)
        self.statusbar.setObjectName("statusbar")
        Playfair.setStatusBar(self.statusbar)

        self.retranslateUi(Playfair)
        QtCore.QMetaObject.connectSlotsByName(Playfair)

    def retranslateUi(self, Playfair):
        _translate = QtCore.QCoreApplication.translate
        Playfair.setWindowTitle(_translate("Playfair", "MainWindow"))
        self.PlayfairCipher.setText(_translate("Playfair", "Playfair Cipher"))
        self.TTCN.setText(_translate("Playfair", "Danh Minh Quốc - 2280618774"))
        self.PlainText.setText(_translate("Playfair", "Plain_text:"))
        self.Key.setText(_translate("Playfair", "Key:"))
        self.CipherText.setText(_translate("Playfair", "Cipher_text:"))
        self.decrypt_btn.setText(_translate("Playfair", "Decrypt"))
        self.encrypt_btn.setText(_translate("Playfair", "Encrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Playfair = QtWidgets.QMainWindow()
    ui = Ui_Playfair()
    ui.setupUi(Playfair)
    Playfair.show()
    sys.exit(app.exec_())
